version: "3.9"
 
services:

  db_01:
    image: mysql
    volumes:
      - db_data_01:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
 
  wordpress_01:
    depends_on:
      - db_01
    image: wordpress:latest
    volumes:
      - wordpress_data_01:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_01:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data_01: {}
  wordpress_data_01: {}